/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author 182220040
 */
public class janelaEdicao extends javax.swing.JFrame {

    /**
     * Creates new form janelaEdicao
     */
    public janelaEdicao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgDisponibilidade = new javax.swing.ButtonGroup();
        janelaEdicao = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        tfNome = new javax.swing.JTextField();
        lbEnunciado = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        lbDescricao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescricao = new javax.swing.JTextArea();
        lbDisponibilidade = new javax.swing.JLabel();
        btRSim = new javax.swing.JRadioButton();
        btRNao = new javax.swing.JRadioButton();
        lbTipo = new javax.swing.JLabel();
        dropTipoProd = new javax.swing.JComboBox<>();
        lbValorProd = new javax.swing.JLabel();
        lbReais = new javax.swing.JLabel();
        tfValorProd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jToggleButton1.setText("Concluir");

        lbEnunciado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbEnunciado.setText("Informe os novos dados para o produto:");

        lbNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNome.setText("Nome:");

        lbDescricao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDescricao.setText("Descrição:");

        taDescricao.setColumns(20);
        taDescricao.setRows(5);
        jScrollPane1.setViewportView(taDescricao);

        lbDisponibilidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDisponibilidade.setText("Disponibilidade:");

        bgDisponibilidade.add(btRSim);
        btRSim.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btRSim.setText("Sim");

        bgDisponibilidade.add(btRNao);
        btRNao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btRNao.setText("Não");

        lbTipo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTipo.setText("Tipo:");

        dropTipoProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Lanche", "Bebida", "Adicional", "Outro..." }));

        lbValorProd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbValorProd.setText("Valor unitário:");

        lbReais.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbReais.setText("R$");

        javax.swing.GroupLayout janelaEdicaoLayout = new javax.swing.GroupLayout(janelaEdicao);
        janelaEdicao.setLayout(janelaEdicaoLayout);
        janelaEdicaoLayout.setHorizontalGroup(
            janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(janelaEdicaoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToggleButton1)
                    .addGroup(janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbDisponibilidade)
                        .addGroup(janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNome)
                            .addComponent(lbDescricao)
                            .addComponent(lbNome)
                            .addComponent(lbEnunciado)
                            .addComponent(jScrollPane1))
                        .addGroup(janelaEdicaoLayout.createSequentialGroup()
                            .addComponent(btRSim)
                            .addGap(4, 4, 4)
                            .addComponent(btRNao))
                        .addComponent(lbTipo)
                        .addComponent(dropTipoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbValorProd)
                        .addGroup(janelaEdicaoLayout.createSequentialGroup()
                            .addComponent(lbReais)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfValorProd, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        janelaEdicaoLayout.setVerticalGroup(
            janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, janelaEdicaoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbEnunciado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbDisponibilidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRSim)
                    .addComponent(btRNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(lbTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dropTipoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbValorProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbReais)
                    .addComponent(tfValorProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(janelaEdicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(janelaEdicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(janelaEdicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(janelaEdicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(janelaEdicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(janelaEdicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new janelaEdicao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgDisponibilidade;
    private javax.swing.JRadioButton btRNao;
    private javax.swing.JRadioButton btRSim;
    private javax.swing.JComboBox<String> dropTipoProd;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel janelaEdicao;
    private javax.swing.JLabel lbDescricao;
    private javax.swing.JLabel lbDisponibilidade;
    private javax.swing.JLabel lbEnunciado;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbReais;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JLabel lbValorProd;
    private javax.swing.JTextArea taDescricao;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfValorProd;
    // End of variables declaration//GEN-END:variables
}
