/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CliController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Cliente;

/**
 *
 * @author felip
 */
public class ViewEdCliente extends javax.swing.JFrame {

    /**
     * Creates new form ViewEdCliente
     */
    public ViewEdCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        janelaEdicao = new javax.swing.JPanel();
        btConcluiEdCli = new javax.swing.JToggleButton();
        lbEnunciado = new javax.swing.JLabel();
        lbNomeCli = new javax.swing.JLabel();
        lbEmailCli = new javax.swing.JLabel();
        lbDataNascCli = new javax.swing.JLabel();
        lbEndCli = new javax.swing.JLabel();
        tfEndCli = new javax.swing.JTextField();
        lbnumEndCli = new javax.swing.JLabel();
        tfNumEndCli = new javax.swing.JTextField();
        tfNomeCli = new javax.swing.JTextField();
        tfEmailCli = new javax.swing.JTextField();
        tfDataNascCli = new javax.swing.JTextField();
        lbTelefoneCli = new javax.swing.JLabel();
        tfTelefoneCli = new javax.swing.JTextField();
        lbBairroCLi = new javax.swing.JLabel();
        tfBairroCli = new javax.swing.JTextField();
        tfCidadeCli = new javax.swing.JTextField();
        lbCidadeCLi = new javax.swing.JLabel();
        lbCompCLi = new javax.swing.JLabel();
        tfCompCli = new javax.swing.JTextField();
        lbSenhaCli = new javax.swing.JLabel();
        lbRepSenhaCli = new javax.swing.JLabel();
        tfSenhaCli = new javax.swing.JTextField();
        tfSenhaRepCli = new javax.swing.JTextField();
        lbUFCLi = new javax.swing.JLabel();
        tfUFCli = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btConcluiEdCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btConcluiEdCli.setText("Concluir");
        btConcluiEdCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConcluiEdCliActionPerformed(evt);
            }
        });

        lbEnunciado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbEnunciado.setText("Edite seus dados de cadastro:");

        lbNomeCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNomeCli.setText("Nome:");

        lbEmailCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbEmailCli.setText("Email:");

        lbDataNascCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDataNascCli.setText("Data de nascimento:");

        lbEndCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbEndCli.setText("Endereço:");

        lbnumEndCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbnumEndCli.setText("Número:");

        lbTelefoneCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTelefoneCli.setText("Telefone:");

        lbBairroCLi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbBairroCLi.setText("Bairro:");

        lbCidadeCLi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCidadeCLi.setText("Cidade:");

        lbCompCLi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCompCLi.setText("Complemento:");

        lbSenhaCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbSenhaCli.setText("Senha:");

        lbRepSenhaCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbRepSenhaCli.setText("Repita a senha:");

        lbUFCLi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbUFCLi.setText("Estado:");

        javax.swing.GroupLayout janelaEdicaoLayout = new javax.swing.GroupLayout(janelaEdicao);
        janelaEdicao.setLayout(janelaEdicaoLayout);
        janelaEdicaoLayout.setHorizontalGroup(
            janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, janelaEdicaoLayout.createSequentialGroup()
                .addGroup(janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(janelaEdicaoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btConcluiEdCli))
                    .addGroup(janelaEdicaoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfEmailCli, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEnunciado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                            .addComponent(tfNomeCli, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(janelaEdicaoLayout.createSequentialGroup()
                                .addGroup(janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfBairroCli, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbBairroCLi))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(janelaEdicaoLayout.createSequentialGroup()
                                        .addComponent(lbCidadeCLi)
                                        .addGap(93, 93, 93))
                                    .addComponent(tfCidadeCli)))
                            .addGroup(janelaEdicaoLayout.createSequentialGroup()
                                .addGroup(janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbEndCli)
                                    .addComponent(tfEndCli, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(janelaEdicaoLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lbnumEndCli)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE))
                                    .addComponent(tfNumEndCli)))
                            .addGroup(janelaEdicaoLayout.createSequentialGroup()
                                .addGroup(janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(janelaEdicaoLayout.createSequentialGroup()
                                        .addComponent(lbUFCLi)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(tfUFCli))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCompCLi)
                                    .addComponent(tfCompCli, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, janelaEdicaoLayout.createSequentialGroup()
                                .addGroup(janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(janelaEdicaoLayout.createSequentialGroup()
                                            .addComponent(tfDataNascCli, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(10, 10, 10))
                                        .addComponent(lbSenhaCli, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfSenhaCli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(janelaEdicaoLayout.createSequentialGroup()
                                        .addGroup(janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbEmailCli, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbNomeCli, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbDataNascCli, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(23, 23, 23)))
                                .addGroup(janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, janelaEdicaoLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                        .addGroup(janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfSenhaRepCli, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, janelaEdicaoLayout.createSequentialGroup()
                                                .addComponent(lbRepSenhaCli)
                                                .addGap(55, 55, 55))))
                                    .addGroup(janelaEdicaoLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(janelaEdicaoLayout.createSequentialGroup()
                                                .addComponent(lbTelefoneCli)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(tfTelefoneCli))))))))
                .addGap(15, 15, 15))
        );
        janelaEdicaoLayout.setVerticalGroup(
            janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, janelaEdicaoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbEnunciado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNomeCli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbEmailCli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEmailCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataNascCli)
                    .addComponent(lbTelefoneCli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDataNascCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTelefoneCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRepSenhaCli)
                    .addComponent(lbSenhaCli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSenhaRepCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSenhaCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEndCli)
                    .addComponent(lbnumEndCli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEndCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNumEndCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBairroCLi)
                    .addComponent(lbCidadeCLi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBairroCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCidadeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCompCLi)
                    .addComponent(lbUFCLi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(janelaEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCompCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfUFCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btConcluiEdCli)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(janelaEdicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(janelaEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConcluiEdCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConcluiEdCliActionPerformed
        CliController pc = new CliController();
        Cliente cli = new Cliente(cpf, nome, senha, email, telefone, dataNasc, endereco, numEndereco, bairro, cidade, complemento, unidade_federativa);
        if(tfSenhaCli.getText().equals(tfSenhaRepCli.getText())){
            pc.Editar(cpfEdicao, tfNomeCli.getText(), tfSenhaCli.getText(), tfEmailCli.getText(), tfTelefoneCli.getText(), tfDataNascCli.getText(), tfEndCli.getText(), tfNumEndCli.getText(), tfBairroCli.getText(), tfCidadeCli.getText(), tfCompCli.getText(), tfUFCli.getText());
            dispose();
        } else{
            JOptionPane.showMessageDialog(null, "Os campos de senha devem ser iguais.");
            tfSenhaCli.setText("");
            tfSenhaRepCli.setText("");
        }
    }//GEN-LAST:event_btConcluiEdCliActionPerformed

    public void recebeInfoEd(ArrayList<String> lista) {
        cpfEdicao = lista.get(0);
        tfNomeCli.setText(lista.get(1));
        tfEmailCli.setText(lista.get(2));
        tfTelefoneCli.setText(lista.get(3));
        tfDataNascCli.setText(lista.get(4));
        tfEndCli.setText(lista.get(5));
        tfNumEndCli.setText(lista.get(6));
        tfCidadeCli.setText(lista.get(7));
        tfUFCli.setText(lista.get(8));
        tfBairroCli.setText(lista.get(9));
        tfCompCli.setText(lista.get(10));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEdCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEdCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEdCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEdCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEdCliente().setVisible(true);
            }
        });
    }
    
    String cpfEdicao;
    private String cpf;
    private String nome;
    private String senha;
    private String email;
    private String telefone;
    private String dataNasc;
    private String endereco;
    private String numEndereco;
    private String bairro;
    private String cidade;
    private String complemento;
    private String unidade_federativa;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btConcluiEdCli;
    private javax.swing.JPanel janelaEdicao;
    private javax.swing.JLabel lbBairroCLi;
    private javax.swing.JLabel lbCidadeCLi;
    private javax.swing.JLabel lbCompCLi;
    private javax.swing.JLabel lbDataNascCli;
    private javax.swing.JLabel lbEmailCli;
    private javax.swing.JLabel lbEndCli;
    private javax.swing.JLabel lbEnunciado;
    private javax.swing.JLabel lbNomeCli;
    private javax.swing.JLabel lbRepSenhaCli;
    private javax.swing.JLabel lbSenhaCli;
    private javax.swing.JLabel lbTelefoneCli;
    private javax.swing.JLabel lbUFCLi;
    private javax.swing.JLabel lbnumEndCli;
    private javax.swing.JTextField tfBairroCli;
    private javax.swing.JTextField tfCidadeCli;
    private javax.swing.JTextField tfCompCli;
    private javax.swing.JTextField tfDataNascCli;
    private javax.swing.JTextField tfEmailCli;
    private javax.swing.JTextField tfEndCli;
    private javax.swing.JTextField tfNomeCli;
    private javax.swing.JTextField tfNumEndCli;
    private javax.swing.JTextField tfSenhaCli;
    private javax.swing.JTextField tfSenhaRepCli;
    private javax.swing.JTextField tfTelefoneCli;
    private javax.swing.JTextField tfUFCli;
    // End of variables declaration//GEN-END:variables
}
